codecov:
  require_ci_to_pass: yes
coverage:
  precision: 1
  round: nearest
  status:
    project:
      default:
        target: auto
        threshold: 1.0
    patch:
      default:
        target: auto
        threshold: 1.0
comment:
  layout: "reach, diff, flags, files"
  require_changes: true
